# Generated by Django 3.2.12 on 2022-03-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20220325_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiazhikehu',
            name='phone',
            field=models.IntegerField(default='13300000000', verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='jiazhikehu',
            name='text',
            field=models.CharField(default='无', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='phone',
            field=models.IntegerField(default='13300000000', verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='text',
            field=models.CharField(default='无', max_length=100, verbose_name='备注'),
        ),
    ]
