# Generated by Django 3.2.12 on 2022-03-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20220325_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='phone',
            field=models.IntegerField(default='13300000000', max_length=50, verbose_name='联系方式'),
        ),
    ]
